---
# tasks file for ntpd

- name: Set OS related variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - defaults.yml

- name: Setup ntp.conf
  ansible.builtin.template:
    src: "ntp.conf.j2"
    dest: "{{ ntp_conf }}"
    mode: "0444"
  notify: "Restart ntp"
  when:
    - ntp_conf is defined
    - ntp_conf is not none
    - ntp_conf | length > 0

- name: Start ntpd
  ansible.builtin.service:
    name: "{{ ntp_service }}"
    enabled: true
    state: started
  when:
    - ntp_service is defined
    - ntp_service is not none
    - ntp_service | length > 0
